# Form implementation generated from reading ui file 'c:\Users\hp\Desktop\VSC\Cloned\Ebook-PR-Application\source\features\ui\SearchPageModified.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1092, 683)
        Form.setMinimumSize(QtCore.QSize(1092, 683))
        Form.setStyleSheet("    QWidget {\n"
"        background-color: #333333;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton {\n"
"        background-color: #4d4d4d;\n"
"        border: 1px solid #4d4d4d;\n"
"        border-radius: 4px;\n"
"        color: #ffffff;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #5a5a5a;\n"
"        border: 1px solid #5a5a5a;\n"
"    }\n"
"    QCheckBox {\n"
"        color: #ffffff;\n"
"    }\n"
"    QLineEdit {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #4d4d4d;\n"
"        color: #000000;\n"
"        padding: 5px;\n"
"    }\n"
"    QTextEdit {\n"
"        background-color: #4d4d4d;\n"
"        border: 1px solid #4d4d4d;\n"
"        color: #ffffff;\n"
"        padding: 5px;\n"
"    }\n"
"    QProgressBar {\n"
"        border: 1px solid #444444;\n"
"        border-radius: 7px;\n"
"        background-color: #2e2e2e;\n"
"        text-align: center;\n"
"        font-size: 10pt;\n"
"        color: white;\n"
"    }\n"
"    QProgressBar::chunk {\n"
"        background-color: #3a3a3a;\n"
"        width: 5px;\n"
"    }\n"
"    QScrollBar:vertical {\n"
"        border: none;\n"
"        background-color: #3a3a3a;\n"
"        width: 10px;\n"
"        margin: 16px 0 16px 0;\n"
"    }\n"
"    QScrollBar::handle:vertical {\n"
"        background-color: #444444;\n"
"        border-radius: 5px;\n"
"    }\n"
"    QScrollBar:horizontal {\n"
"        border: none;\n"
"        background-color: #3a3a3a;\n"
"        height: 10px;\n"
"        margin: 0px 16px 0 16px;\n"
"    }\n"
"    QScrollBar::handle:horizontal {\n"
"        background-color: #444444;\n"
"        border-radius: 5px;\n"
"    }\n"
"    QTabWidget {\n"
"        background-color: #2e2e2e;\n"
"        border: none;\n"
"    }\n"
"    QTabBar::tab {\n"
"        background-color: #2e2e2e;\n"
"        color: #b1b1b1;\n"
"        padding: 8px 20px;\n"
"        border-top-left-radius: 5px;\n"
"        border-top-right-radius: 5px;\n"
"        border: none;\n"
"    }\n"
" \n"
"    QTabBar::tab:selected, QTabBar::tab:hover {\n"
"        background-color: #3a3a3a;\n"
"        color: white;\n"
"    }")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 50, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setStyleSheet("font: 700 55pt \"Segoe UI\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setMinimumSize(QtCore.QSize(500, 50))
        self.lineEdit.setMaximumSize(QtCore.QSize(1200, 50))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    \n"
"    color: #333333;\n"
"    border: 1px solid #999; /* Border color */\n"
"    padding: 5px; /* Padding inside the combo box */\n"
"    color: #333333;\n"
"    font-size: 20px; /* Replace with your desired font size */\n"
"    font-weight: bold; /* Make the text bold */\n"
"    \n"
"\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.search_ebook = QtWidgets.QPushButton(parent=Form)
        self.search_ebook.setMinimumSize(QtCore.QSize(100, 50))
        self.search_ebook.setMaximumSize(QtCore.QSize(200, 50))
        self.search_ebook.setStyleSheet("font: 700 15pt \"Segoe UI\";")
        self.search_ebook.setObjectName("search_ebook")
        self.horizontalLayout_2.addWidget(self.search_ebook)
        self.cancel_search = QtWidgets.QPushButton(parent=Form)
        self.cancel_search.setMinimumSize(QtCore.QSize(100, 50))
        self.cancel_search.setMaximumSize(QtCore.QSize(200, 50))
        self.cancel_search.setStyleSheet("font: 700 15pt \"Segoe UI\";")
        self.cancel_search.setObjectName("cancel_search")
        self.horizontalLayout_2.addWidget(self.cancel_search)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(100, -1, 100, 330)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radio_button_1 = QtWidgets.QRadioButton(parent=Form)
        self.radio_button_1.setStyleSheet("font: 700 25pt \"Segoe UI\";")
        self.radio_button_1.setObjectName("radio_button_1")
        self.horizontalLayout_3.addWidget(self.radio_button_1)
        self.radio_button_2 = QtWidgets.QRadioButton(parent=Form)
        self.radio_button_2.setStyleSheet("font: 700 25pt \"Segoe UI\";")
        self.radio_button_2.setObjectName("radio_button_2")
        self.horizontalLayout_3.addWidget(self.radio_button_2)
        self.radio_button_3 = QtWidgets.QRadioButton(parent=Form)
        self.radio_button_3.setStyleSheet("font: 700 25pt \"Segoe UI\";")
        self.radio_button_3.setObjectName("radio_button_3")
        self.horizontalLayout_3.addWidget(self.radio_button_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "E-Book Search"))
        self.search_ebook.setText(_translate("Form", "Search"))
        self.cancel_search.setText(_translate("Form", "Cancel"))
        self.radio_button_1.setText(_translate("Form", "OCN"))
        self.radio_button_2.setText(_translate("Form", "Title"))
        self.radio_button_3.setText(_translate("Form", "eISBN"))
